apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: argocd_deploy
    repoURL: https://github.com/Aleger4/GitOps-workshop.git
    targetRevision: HEAD
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
